baseurl = "https://donw.io/"
languageCode = "en-us"
title = "Gazoo.vrv"

[taxonomies]
tag = "tags"

[params]
 author = "Don Williamson"
 description = "Don Williamson, Consultant Game Technology Programmer/Director of Celtoys"
 twitter = "Donzanoid"
 github = "dwilliamson"
 github2 = "Celtoys"
 bitbucket = "dwilliamson"