name = "Detox"
license = "MIT"
licenselink = "https://github.com/allnightgrocery/hugo-theme-blueberry-detox/blob/master/LICENSE"
description = "Detox is a beautiful theme, originally designed by Jordan Bowman (@jrdnbwmn)."
homepage = "https://github.com/allnightgrocery/hugo-theme-blueberry-detox"
tags = ["blog", "minimal", "ghost", "white"]
features = ["blog", "disqus", "google analytics", "pagination", "rss", "sharing options"]
min_version = 0.14

[author]
  name = "Andrew R. Jenkins"
  homepage = "http://andrewrjenkins.com"

# If porting an existing theme
[original]
  name = "Jordan Bowman"
  homepage = "http://www.jrdnbwmn.com"
  repo = "https://github.com/jrdnbwmn/detox"
